# Generated by Django 4.2.11 on 2026-04-13 16:37

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("reader", "Reader"),
                            ("journalist", "Journalist"),
                            ("editor", "Editor"),
                            ("admin", "Admin"),
                        ],
                        default="reader",
                        help_text="User role determines permissions and access levels",
                        max_length=20,
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Short biography for content creators",
                        max_length=500,
                    ),
                ),
                (
                    "profile_image",
                    models.URLField(blank=True, help_text="URL to profile image"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Article title", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                            ("archived", "Archived"),
                        ],
                        default="pending",
                        help_text="Article publication status",
                        max_length=20,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Reason for rejection (if applicable)"
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, help_text="Creation date"),
                ),
                (
                    "published_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when article was published",
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True, help_text="URL to article image", null=True
                    ),
                ),
                ("content", models.TextField(help_text="Article content")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Article author (journalist)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bookmarked_by",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Users who bookmarked this article",
                        related_name="bookmarked_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "articles",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the category"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this category is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Publisher organization name",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of the publisher"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Publisher website URL"),
                ),
                ("logo", models.URLField(blank=True, help_text="Publisher logo URL")),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verification status of the publisher"
                    ),
                ),
                (
                    "is_independent",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is an independent publisher",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Publisher",
                "verbose_name_plural": "Publishers",
                "db_table": "publishers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Newsletter title", max_length=200),
                ),
                (
                    "subject",
                    models.CharField(help_text="Email subject line", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        help_text="Newsletter status",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Newsletter content")),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, help_text="When to send the newsletter", null=True
                    ),
                ),
                (
                    "sent_date",
                    models.DateTimeField(
                        blank=True, help_text="When the newsletter was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "article",
                    models.ForeignKey(
                        blank=True,
                        help_text="Featured article in this newsletter",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="articles.article",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        help_text="Newsletter author (journalist)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Newsletter category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="articles.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Newsletter",
                "verbose_name_plural": "Newsletters",
                "db_table": "newsletters",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Journalist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        help_text="Area of journalism specialization",
                        max_length=200,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Verification status of the journalist"
                    ),
                ),
                (
                    "total_articles_written",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of articles written by this journalist",
                    ),
                ),
                (
                    "total_newsletters_sent",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Count of newsletters sent by this journalist",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Publisher organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journalists",
                        to="articles.publisher",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated journalist user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journalist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journalist",
                "verbose_name_plural": "Journalists",
                "db_table": "journalists",
            },
        ),
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, help_text="Editorial department", max_length=100
                    ),
                ),
                (
                    "is_chief_editor",
                    models.BooleanField(
                        default=False, help_text="Whether this is a chief/senior editor"
                    ),
                ),
                (
                    "articles_reviewed",
                    models.PositiveIntegerField(
                        default=0, help_text="Count of articles reviewed by this editor"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Associated editor user account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Editor",
                "verbose_name_plural": "Editors",
                "db_table": "editors",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                help_text="Article category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="articles.category",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Editor who reviewed this article",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="Publisher organization this user belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="articles.publisher",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "journalist",
                    models.ForeignKey(
                        blank=True,
                        help_text="Journalist being subscribed to",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        help_text="Publisher being subscribed to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="articles.publisher",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        help_text="User who is subscribing",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "db_table": "subscriptions",
                "unique_together": {("subscriber", "publisher", "journalist")},
            },
        ),
    ]
