# Generated by Django 4.2.11 on 2026-04-14 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="article",
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscribed_journalists",
            field=models.ManyToManyField(
                blank=True,
                help_text="Journalists this user has subscribed to",
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="subscribed_publishers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Publishers this user has subscribed to",
                related_name="subscribers",
                to="articles.publisher",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="articles",
            field=models.ManyToManyField(
                blank=True,
                help_text="Articles featured in this newsletter",
                related_name="newsletters",
                to="articles.article",
            ),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
